version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: analytics
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ../backend
    depends_on: ['postgres']
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/analytics
    ports:
      - '4000:4000'
  frontend:
    build: ../frontend
    depends_on: ['backend']
    ports:
      - '3000:3000'
volumes:
  db-data: